import { afterAll, describe, expect, it } from "bun:test";
import { eq } from "drizzle-orm";
import { uuidv7 } from "uuidv7";
import { db, sql } from "../../../../config/database";
import { items as itemsTable } from "../schema";
import { PostgresItemRepository } from "./item.repository";

/**
 * Integration Test Suite: PostgresItemRepository
 *
 * These tests run against a real PostgreSQL connection (loaded from .env)
 * to verify that the Drizzle ORM adapter correctly implements the ItemRepository
 * port contract at the database level.
 *
 * Test isolation strategy:
 * - Each suite execution creates a uniquely named root folder via uuidv7.
 * - All child items are nested under this root so they are self-contained.
 * - `afterAll` deletes the root record; any children are removed via DB cascade.
 * - `sql.end()` cleanly closes the connection pool after the suite finishes.
 *
 * Tests run sequentially and share state via `testRootId` to simulate a
 * realistic create → read → verify → delete lifecycle.
 */
describe("PostgresItemRepository Integration Tests", () => {
  const repository = new PostgresItemRepository();
  let testRootId: string;

  // Cleanup: Remove any test data after assertions finish
  const cleanup = async () => {
    if (testRootId) {
      await db.delete(itemsTable).where(eq(itemsTable.id, testRootId));
    }
  };

  afterAll(async () => {
    await cleanup();
    await sql.end();
  });

  /**
   * Test 1 — Create
   *
   * Purpose:
   *   Verifies that `repository.create()` correctly inserts a root-level folder
   *   (parentId: null) into PostgreSQL and returns the persisted entity.
   *
   * Expected result:
   *   - The returned object has a defined `id` (generated by the DB via uuidv7).
   *   - The `type` field is preserved as "folder".
   *   - `testRootId` is captured so subsequent tests can nest children under it.
   */
  it("should securely create a root integration folder", async () => {
    const root = await repository.create({
      name: `integration_test_root_${uuidv7()}`,
      type: "folder",
      parentId: null,
      path: "",
      depth: 0,
      sortOrder: 0,
      size: 0,
      mimeType: null,
    });

    expect(root.id).toBeDefined();
    expect(root.type).toBe("folder");
    testRootId = root.id;
  });

  /**
   * Test 2 — Pagination
   *
   * Purpose:
   *   Verifies that `findChildrenByParentId()` correctly applies `limit` and `offset`
   *   and returns an accurate `total` count independent of the page size.
   *
   *   Inserts 5 items (2 folders + 3 files) under `testRootId`, then queries
   *   with `limit=3` and `offset=0` to simulate the first page of an infinite scroll.
   *
   * Expected result:
   *   - `data.length` is 3 (only the first page is returned).
   *   - `total` is 5 (the count query reflects all children, not just the fetched page).
   *   This confirms the client can compute `hasMoreChildren = data.length < total`.
   */
  it("should create children and verify pagination offset sizes", async () => {
    // Insert 2 folders + 3 files = 5 total children under testRootId
    await repository.create({
      name: "Folder A",
      type: "folder",
      parentId: testRootId,
      path: `/${testRootId}`,
      depth: 1,
      sortOrder: 1,
      size: 0,
      mimeType: null,
    });
    await repository.create({
      name: "File A",
      type: "file",
      parentId: testRootId,
      path: `/${testRootId}`,
      depth: 1,
      sortOrder: 2,
      size: 1024,
      mimeType: "text/plain",
    });
    await repository.create({
      name: "Folder B",
      type: "folder",
      parentId: testRootId,
      path: `/${testRootId}`,
      depth: 1,
      sortOrder: 3,
      size: 0,
      mimeType: null,
    });
    await repository.create({
      name: "File B",
      type: "file",
      parentId: testRootId,
      path: `/${testRootId}`,
      depth: 1,
      sortOrder: 4,
      size: 2048,
      mimeType: "text/plain",
    });
    await repository.create({
      name: "File C",
      type: "file",
      parentId: testRootId,
      path: `/${testRootId}`,
      depth: 1,
      sortOrder: 5,
      size: 3000,
      mimeType: "text/plain",
    });

    // Request page 1: limit=3, offset=0
    const { data, total } = await repository.findChildrenByParentId(
      testRootId,
      3,
      0,
    );

    expect(data.length).toBe(3); // Only 3 items returned (first page)
    expect(total).toBe(5); // Count query reflects all 5 children
  });

  /**
   * Test 3 — Folder-First Ordering
   *
   * Purpose:
   *   Verifies that the SQL `ORDER BY CASE WHEN type = 'folder' THEN 0 ELSE 1 END ASC`
   *   expression correctly places all folders before all files in every query result,
   *   regardless of insertion order, alphabetical order, or sort_order values.
   *
   *   The 5 items were inserted in mixed order: Folder A → File A → Folder B → File B → File C.
   *   Without the CASE expression, a naive alphabetical sort would place File A before Folder B.
   *
   * Expected result:
   *   - Indices 0 and 1 are both type "folder" (Folder A, Folder B).
   *   - Indices 2, 3, and 4 are all type "file" (File A, File B, File C).
   *   This guarantees the UI always renders folders at the top of any content panel.
   */
  it("should scientifically enforce folder-first ordering (CASE ASC behavior)", async () => {
    // Fetch all 5 children with no page limit to inspect the full ordered result
    const { data } = await repository.findChildrenByParentId(testRootId, 10, 0);

    expect(data.length).toBe(5);

    // First two positions must be folders
    expect(data[0].type).toBe("folder");
    expect(data[1].type).toBe("folder");

    // Remaining three positions must be files
    expect(data[2].type).toBe("file");
    expect(data[3].type).toBe("file");
    expect(data[4].type).toBe("file");
  });

  /**
   * Test 4 — Delete & Cascade
   *
   * Purpose:
   *   Verifies that `repository.delete()` removes the target record from PostgreSQL,
   *   and that any child records are cleaned up via the database ON DELETE CASCADE
   *   constraint defined in the Drizzle schema (parentId → id foreign key).
   *
   * Expected result:
   *   - `findById(testRootId)` returns `null` after deletion.
   *   - `testRootId` is reset to `""` so the `afterAll` cleanup hook is a safe no-op.
   */
  it("should cleanly tear down an item", async () => {
    await repository.delete(testRootId);

    const found = await repository.findById(testRootId);
    expect(found).toBeNull();

    // Reset so afterAll cleanup does not attempt a redundant delete
    testRootId = "";
  });
});
